#############################################################################
# Makefile for building: vlcstreamer
# Generated by qmake (2.01a) (Qt 4.8.2) on: Tue Jun 12 11:57:56 2012
# Project:  VlcStreamer.pro
# Template: app
# Command: /bin/qmake -o Makefile VlcStreamer.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -O2 -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -O2 -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/lib64/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib64 -lqjson -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		VlcEncoder.cpp \
		VlcEncodingSystem.cpp \
		VlcStreamerApp.cpp \
		VlcStreamerConnection.cpp \
		VlcStreamerServer.cpp moc_VlcEncodingSystem.cpp \
		moc_VlcStreamerApp.cpp \
		moc_VlcStreamerConnection.cpp \
		moc_VlcStreamerServer.cpp
OBJECTS       = main.o \
		VlcEncoder.o \
		VlcEncodingSystem.o \
		VlcStreamerApp.o \
		VlcStreamerConnection.o \
		VlcStreamerServer.o \
		moc_VlcEncodingSystem.o \
		moc_VlcStreamerApp.o \
		moc_VlcStreamerConnection.o \
		moc_VlcStreamerServer.o
DIST          = /usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt4/mkspecs/common/g++-base.conf \
		/usr/lib64/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf \
		VlcStreamer.pro
QMAKE_TARGET  = vlcstreamer
DESTDIR       = 
TARGET        = vlcstreamer

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: VlcStreamer.pro  /usr/lib64/qt4/mkspecs/linux-g++/qmake.conf /usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt4/mkspecs/common/g++-base.conf \
		/usr/lib64/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/libQtNetwork.prl \
		/usr/lib64/libQtCore.prl
	$(QMAKE) -o Makefile VlcStreamer.pro
/usr/lib64/qt4/mkspecs/common/unix.conf:
/usr/lib64/qt4/mkspecs/common/linux.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt4/mkspecs/common/g++-base.conf:
/usr/lib64/qt4/mkspecs/common/g++-unix.conf:
/usr/lib64/qt4/mkspecs/qconfig.pri:
/usr/lib64/qt4/mkspecs/features/qt_functions.prf:
/usr/lib64/qt4/mkspecs/features/qt_config.prf:
/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt4/mkspecs/features/default_pre.prf:
/usr/lib64/qt4/mkspecs/features/release.prf:
/usr/lib64/qt4/mkspecs/features/default_post.prf:
/usr/lib64/qt4/mkspecs/features/qt.prf:
/usr/lib64/qt4/mkspecs/features/unix/thread.prf:
/usr/lib64/qt4/mkspecs/features/moc.prf:
/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib64/qt4/mkspecs/features/warn_on.prf:
/usr/lib64/qt4/mkspecs/features/resources.prf:
/usr/lib64/qt4/mkspecs/features/uic.prf:
/usr/lib64/qt4/mkspecs/features/yacc.prf:
/usr/lib64/qt4/mkspecs/features/lex.prf:
/usr/lib64/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/libQtNetwork.prl:
/usr/lib64/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile VlcStreamer.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/vlcstreamer1.0.0 || $(MKDIR) .tmp/vlcstreamer1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/vlcstreamer1.0.0/ && $(COPY_FILE) --parents VlcEncoder.h VlcEncodingSystem.h VlcStreamerApp.h VlcStreamerConnection.h VlcStreamerServer.h .tmp/vlcstreamer1.0.0/ && $(COPY_FILE) --parents main.cpp VlcEncoder.cpp VlcEncodingSystem.cpp VlcStreamerApp.cpp VlcStreamerConnection.cpp VlcStreamerServer.cpp .tmp/vlcstreamer1.0.0/ && (cd `dirname .tmp/vlcstreamer1.0.0` && $(TAR) vlcstreamer1.0.0.tar vlcstreamer1.0.0 && $(COMPRESS) vlcstreamer1.0.0.tar) && $(MOVE) `dirname .tmp/vlcstreamer1.0.0`/vlcstreamer1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/vlcstreamer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_VlcEncodingSystem.cpp moc_VlcStreamerApp.cpp moc_VlcStreamerConnection.cpp moc_VlcStreamerServer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_VlcEncodingSystem.cpp moc_VlcStreamerApp.cpp moc_VlcStreamerConnection.cpp moc_VlcStreamerServer.cpp
moc_VlcEncodingSystem.cpp: VlcEncodingSystem.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) VlcEncodingSystem.h -o moc_VlcEncodingSystem.cpp

moc_VlcStreamerApp.cpp: VlcStreamerServer.h \
		VlcStreamerApp.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) VlcStreamerApp.h -o moc_VlcStreamerApp.cpp

moc_VlcStreamerConnection.cpp: VlcStreamerConnection.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) VlcStreamerConnection.h -o moc_VlcStreamerConnection.cpp

moc_VlcStreamerServer.cpp: VlcStreamerServer.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) VlcStreamerServer.h -o moc_VlcStreamerServer.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp VlcStreamerApp.h \
		VlcStreamerServer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

VlcEncoder.o: VlcEncoder.cpp VlcEncoder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VlcEncoder.o VlcEncoder.cpp

VlcEncodingSystem.o: VlcEncodingSystem.cpp VlcEncodingSystem.h \
		VlcEncoder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VlcEncodingSystem.o VlcEncodingSystem.cpp

VlcStreamerApp.o: VlcStreamerApp.cpp VlcStreamerApp.h \
		VlcStreamerServer.h \
		VlcEncodingSystem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VlcStreamerApp.o VlcStreamerApp.cpp

VlcStreamerConnection.o: VlcStreamerConnection.cpp VlcStreamerConnection.h \
		VlcStreamerApp.h \
		VlcStreamerServer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VlcStreamerConnection.o VlcStreamerConnection.cpp

VlcStreamerServer.o: VlcStreamerServer.cpp VlcStreamerServer.h \
		VlcStreamerConnection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VlcStreamerServer.o VlcStreamerServer.cpp

moc_VlcEncodingSystem.o: moc_VlcEncodingSystem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_VlcEncodingSystem.o moc_VlcEncodingSystem.cpp

moc_VlcStreamerApp.o: moc_VlcStreamerApp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_VlcStreamerApp.o moc_VlcStreamerApp.cpp

moc_VlcStreamerConnection.o: moc_VlcStreamerConnection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_VlcStreamerConnection.o moc_VlcStreamerConnection.cpp

moc_VlcStreamerServer.o: moc_VlcStreamerServer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_VlcStreamerServer.o moc_VlcStreamerServer.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

